#!/bin/bash


function up() {

  echo "
  moving up to destination directory
  "
  sudo cp -rfv up /usr/bin/
  sudo cp -rfv up /usr/sbin/
  echo "
  completed
  "
}

function ask() {

  echo "
  moving ask to destination directory
  "
  sudo cp -rfv ./lib/ask /usr/bin/
  sudo cp -rfv ./lib/ask /usr/sbin/
  echo "
  completed
  "
}

function main() {
  up
  ask
}

main