#!/bin/bash

function ask() {
  # https://djm.me/ask
  local prompt default reply

  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -n "$1 [$prompt] "

    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read reply </dev/tty

    # Default?
    if [ -z "$reply" ]; then
      reply=$default
    fi

    # Check if the reply is valid
    case "$reply" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}

function update() {
  sudo apt update
  sudo apt full-upgrade -y
  sudo apt autoremove -y
}

function tweak() {
  dpkg -l | grep -qw unity-tweak-tool ||sudo apt install unity-tweak-tool -y
  sudo apt install caffeine -y
  sudo apt-get install indicator-cpufreq -y
  sudo apt-get install indicator-multiload -y
}

function tools() {
  dpkg -l | grep -qw gdebi || sudo apt-get install -y gdebi
  dpkg -l | grep -qw openssh-server ||sudo apt install openssh-server -y
  dpkg -l | grep -qw curl || sudo apt install curl wget -y
  dpkg -l | grep -qw git || sudo apt install git -y
  dpkg -l | grep -qw htop || sudo apt install htop -y
  dpkg -l | grep -qw glances ||sudo apt install glances -y
  dpkg -l | grep -qw nmap || sudo apt install nmap -y
  dpkg -l | grep -qw arp-scan || sudo apt-get install arp-scan -y
  dpkg -l | grep -qw mc || sudo apt install mc -y
  dpkg -l | grep -qw zsh || sudo apt install zsh -y
  dpkg -l | grep -qw terminator || sudo apt install terminator -y
  dpkg -l | grep -qw remmina || sudo apt install remmina remmina-plugin-rdp libfreerdp-plugins-standard -y
}

function albert() {
  sudo add-apt-repository ppa:nilarimogard/webupd8 -y
  sudo apt update
  sudo apt install albert -y
}

function wine() {
  wget https://dl.winehq.org/wine-builds/Release.key
  sudo apt-key add Release.key && sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'
  sudo apt-get update
  sudo apt-get install --install-recommends winehq-stable -y
}

function neo() {
  sudo add-apt-repository ppa:dawidd0811/neofetch -y
  sudo apt update
  sudo apt install neofetch -y
}

function thunderbird() {
  sudo add-apt-repository ppa:mozillateam/thunderbird-next -y
  sudo apt update
  sudo apt install thunderbird -y
}

function vscode() {
  curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  sudo apt update && sudo apt install code -y
}

function help() {

  echo "

  up version 1.0.1 (C) 2018 Bartek \"ubikOne\" Błażejewski
  Released under the GNU GPL.

  System setup tool,
  for debian and debian based linux/gnu distributions.

  start will instal programs and tools on your system,
  such as e.g. mc, htop, vscode, java8, node.js etc.
  

  -h --help          Print this help screen
  -v --version      Print version info


  for more visit https://github.com/ubikOne/scripts

  "

}

function version() {

  echo "version 0.3"

}

function main() {
  if [ "$1" == "--help" ] || [ "$1" == "-h" ]; 
    then
      help
      exit
  fi

  if [ "$1" == "--version" ] || [ "$1" == "-v" ]; 
    then
      version
      exit
  fi
  update
  if ask "
  Ubuntu 16.04?
  " N;
    then
    echo "
    Installing:
    |_ unity tweak tool
    |_ caffeine
    |_ multiload indicator
    |_ cpufreq indicator
    "
    tweak
  fi
  if ask "
  Do you want to install:
  |_ gdebi
  |_ curl 
  |_ wget 
  |_ git 
  |_ htop 
  |_ glances 
  |_ nmap 
  |_ mc 
  |_ arp-scan
  |_ zsh
  |_ ssh server
  |_ terminator
  |_ remmina
  " Y;
    then
    tools
  else
    echo "
    You choose not to install
    "
  fi
  if ask "
  Do you want to install albert omni laucher?
  " Y;
    then
    albert
  else
    echo "
    You choose not to install
    "
  fi
  if ask "
  Do you want to install wine 3.0?
  " Y;
    then
    wine
  else
    echo "
    You choose not to install
    "
  fi
  if ask "
  Do you want to install neofetch?
  " Y;
    then
    neo
  else
    echo "
    You choose not to install
    "
  fi
  if ask "
  Do you want to install vscode?
  " Y;
    then
    vscode
  else
    echo "
    You choose not to install
    "
  fi
}

main $1
