#!/bin/bash

function ask() {
  # https://djm.me/ask
  local prompt default reply

  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -n "$1 [$prompt] "

    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read reply </dev/tty

    # Default?
    if [ -z "$reply" ]; then
      reply=$default
    fi

    # Check if the reply is valid
    case "$reply" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}

function update() {

  sudo apt update

}

function upgrade() {

  sudo apt upgrade -y

}

function fullUpgrade() {

  sudo apt full-upgrade -y

}

function show() {

  sudo apt list --upgradable

}

function remove() {

  sudo apt autoremove -y

}

function help() {

  echo "

  up version 1.0 (C) 2018 Bartek \"ubikOne\" Błażejewski
  Released under the GNU GPL.

  System update & upgrade tool,
  for debian and debian based linux/gnu distributions

  -u --full-upgrade  updating packages and full upgrade of system
  -r --remove        autoremoving orphan packages and dependencies
  -h --help          Print this help screen
  -v -- version      Print version info


  for more visit https://github.com/ubikOne/scripts

  "

}

function version() {

  echo "version 1.0"

}

function main() {

  update
  if ask "Display packages to upgrade?" N; 
    then
    show
  else
  echo ""
  fi
  upgrade

  if [ "$1" == "--full-upgrade" ] || [ "$1" == "-u" ]; 
    then
      update
      if ask "Display packages to upgrade?"  N; 
        then
        show
      else
      echo ""
      fi
      fullUpgrade
  fi

  if [ "$1" == "--remove" ] || [ "$1" == "-r" ]; 
    then
      remove
  fi

  if [ "$1" == "--help" ] || [ "$1" == "-h" ]; 
    then
      help
  fi

  if [ "$1" == "--version" ] || [ "$1" == "-v" ]; 
    then
      version
  fi

}

main $1 