#!/bin/bash

# inporting from libary
./lib/ask.sh

function update() {

  sudo apt update

}

function upgrade() {

  sudo apt upgrade -y

}

function fullUpgrade() {

  sudo apt full-upgrade -y

}

function show() {

  sudo apt list --upgradable

}

function remove() {

  sudo apt autoremove -y

}

function help() {

  echo "

  up version 1.0.2 (C) 2018 Bartek \"ubikOne\" Błażejewski
  Released under the GNU GPL.

  System update & upgrade tool,
  for debian and debian based linux/gnu distributions.

  -u --upgrade       update the apt cache and then perform a
                     standard upgrade
  -U --full-upgrade  update the apt cache and then perform a
                     full distribution update
  -r --remove        autoremoving orphan packages and dependencies
  -h --help          Print this help screen
  -v --version      Print version info


  for more visit https://github.com/ubikOne/scripts

  "

}

function version() {

  echo "version 1.0.2"

}

function main() {

  echo "
  Not know what do do?

  -u --upgrade       update the apt cache and then perform a
                     standard upgrade
  -U --full-upgrade  update the apt cache and then perform a
                     full distribution update
  "

  if [ "$1" == "-upgrade" ] || [ "$1" == "-u" ]; 
    then
      update
      if ask "Display packages to upgrade?"  N; 
        then
        show
      else
      echo ""
      fi
      upgrade
  fi

  if [ "$1" == "--full-upgrade" ] || [ "$1" == "-U" ]; 
    then
      update
      if ask "Display packages to upgrade?"  N; 
        then
        show
      else
      echo ""
      fi
      fullUpgrade
  fi

  if [ "$1" == "--remove" ] || [ "$1" == "-r" ]; 
    then
      remove
  fi

  if [ "$1" == "--help" ] || [ "$1" == "-h" ]; 
    then
      help
  fi

  if [ "$1" == "--version" ] || [ "$1" == "-v" ]; 
    then
      version
  fi

}

main $1 
