#!/bin/bash

ver=1.0.3

function update() {

  sudo apt update

}

function upgrade() {

  sudo apt upgrade -y

}

function fullUpgrade() {

  sudo apt full-upgrade -y

}

function show() {

  sudo apt list --upgradable

}

function remove() {

  sudo apt autoremove -y

}

function help() {

  echo "

  up version $ver (C) 2018 Bartek \"ubikOne\" Błażejewski
  Released under the GNU GPL.

  System update & upgrade tool,
  for debian and debian based linux/gnu distributions.

  -u --upgrade       update the apt cache and then perform a
                     standard upgrade
  -U --full-upgrade  update the apt cache and then perform a
                     full distribution update
  -r --remove        autoremoving orphan packages and dependencies
  -h --help          Print this help screen
  -v --version       Print version info


  for more visit https://github.com/ubikOne/scripts

  "

}

function version() {

  echo "version $ver"

}

function main() {

  if [ $# -eq 0 ]; 
    then
      echo ""
      echo "What you want to do?"
      echo ""
      echo "-u --upgrade       update the apt cache and then perform a"
      echo "                   standard upgrade"
      echo "-U --full-upgrade  update the apt cache and then perform a"
      echo "                   full distribution update"
      echo "-h --help          Print this help screen"
      echo ""
  fi

  if [ "$1" == "-upgrade" ] || [ "$1" == "-u" ]; 
    then
      update
      if ask "Display packages to upgrade?"  N; 
        then
        show
      else
      echo ""
      fi
      upgrade
  fi

  if [ "$1" == "--full-upgrade" ] || [ "$1" == "-U" ]; 
    then
      update
      if ask "Display packages to upgrade?"  N; 
        then
        show
      else
      echo ""
      fi
      fullUpgrade
  fi

  if [ "$1" == "--remove" ] || [ "$1" == "-r" ]; 
    then
      remove
  fi

  if [ "$1" == "--help" ] || [ "$1" == "-h" ]; 
    then
      help
  fi

  if [ "$1" == "--version" ] || [ "$1" == "-v" ]; 
    then
      version
  fi

}

main $1 
